#!/usr/bin/env python3
from client import Client
import tkinter as tk

ASSEMBLY_CENTERS = [
    "Caltech",
    "UVA",
    "Milano",
    "CERN"
]

NUMBER_OF_MODULES = [str(i) for i in range(1,13)]
NUMBER_OF_BOARDS = [str(i) for i in range(1,5)]

def take_data():
    n_boards = n_boards_var.get()
    n_modules = n_modules_var.get()
    
    client = Client()

    # First, we try to get the stepper to the home position
    if stepper_enable.get():
        print("sending command step_home")
        try:
            client.query("step_home")
        except Exception as e:
            entry.delete(0,tk.END)
            entry.insert(0,str(e))

def step_home():
    client = Client()
    try:
        client.query("step_home")
    except Exception as e:
        entry.delete(0,tk.END)
        entry.insert(0,str(e))

window = tk.Tk()

frame_menu = tk.Frame()
frame_settings = tk.Frame()
frame_log = tk.Frame()
frame_buttons = tk.Frame()

entry = tk.Entry(master=frame_log,width=50)
entry.pack()

button_home = tk.Button(master=frame_buttons,text="Stepper Home", width=25, height=5, command=step_home)
button_home.pack()

button = tk.Button(master=frame_buttons,text="Take Data", width=25, height=5, command=take_data)
button.pack()

assembly_center = tk.StringVar(frame_menu)
assembly_center.set(ASSEMBLY_CENTERS[0])

assembly_center_label = tk.Label(frame_menu,text="Assembly Center: ")
assembly_center_label.grid(row=0,column=0)

assembly_center_menu = tk.OptionMenu(frame_menu, assembly_center, *ASSEMBLY_CENTERS)
assembly_center_menu.grid(row=0,column=1)

n_modules_label = tk.Label(frame_menu,text="Number of Modules: ")
n_modules_label.grid(row=1,column=0)

n_modules_var = tk.StringVar(frame_menu)
n_modules_var.set(NUMBER_OF_MODULES[0])

n_modules_menu = tk.OptionMenu(frame_menu, n_modules_var, *NUMBER_OF_MODULES)
n_modules_menu.grid(row=1,column=1)

n_boards_label = tk.Label(frame_menu,text="Number of Boards: ")
n_boards_label.grid(row=2,column=0)

n_boards_var = tk.StringVar(frame_menu)
n_boards_var.set(NUMBER_OF_BOARDS[0])

n_boards_menu = tk.OptionMenu(frame_menu, n_boards_var, *NUMBER_OF_BOARDS)
n_boards_menu.grid(row=2,column=1)

stepper_enable = tk.IntVar(frame_settings, value=1)
stepper_enable_checkbox = tk.Checkbutton(frame_settings, text='Enable Stepper', variable=stepper_enable, onvalue=1, offvalue=0)
stepper_enable_checkbox.pack()

frame_menu.grid(row=0,column=0)
frame_settings.grid(row=0,column=1)
frame_log.grid(row=1,column=0)
frame_buttons.grid(row=1,column=1)

window.mainloop()
